digraph "CFG forkotlinx.coroutines.JobSupport.getCancellationException()Ljava\/util\/concurrent\/CancellationException;" {
Node_23 [shape=record,label="{23\:\ ?|MTH_ENTER_BLOCK\l}"];
Node_25 [shape=record,label="{25\:\ 0x0000|java.lang.Object r0 = getState$kotlinx_coroutines_core()\lr3 = null\l}"];
Node_26 [shape=record,label="{26\:\ 0x0009|if ((r0 instanceof kotlinx.coroutines.JobSupport.Finishing) == false) goto L11\l}"];
Node_27 [shape=record,label="{27\:\ 0x000b|java.lang.Throwable r1 = ((kotlinx.coroutines.JobSupport.Finishing) r0).getRootCause()\l}"];
Node_28 [shape=record,label="{28\:\ 0x0012|if (r1 != null) goto L5\l}"];
Node_30 [shape=record,label="{30\:\ 0x0015|java.util.concurrent.CancellationException r3 = toCancellationException(r1, kotlin.jvm.internal.Intrinsics.stringPlus(kotlinx.coroutines.DebugStrings.getClassSimpleName(r5), \" is cancelling\"))\l}"];
Node_31 [shape=record,label="{31\:\ 0x0023|PHI: r3 \l  PHI: (r3v4 java.util.concurrent.CancellationException) = (r3v0 java.util.concurrent.CancellationException), (r3v7 java.util.concurrent.CancellationException) binds: [B:28:0x0012, B:30:0x0015] A[DONT_GENERATE, DONT_INLINE]\l|if (r3 == null) goto L7\l}"];
Node_33 [shape=record,label="{33\:\ 0x0026}"];
Node_34 [shape=record,label="{34\:\ 0x0033|throw new java.lang.IllegalStateException(kotlin.jvm.internal.Intrinsics.stringPlus(\"Job is still new or active: \", r5).toString())\l}"];
Node_24 [shape=record,label="{24\:\ ?|MTH_EXIT_BLOCK\l}"];
Node_45 [shape=record,label="{45\:\ ?|SYNTHETIC\lRETURN\l|return r3\l}"];
Node_35 [shape=record,label="{35\:\ 0x0034}"];
Node_36 [shape=record,label="{36\:\ 0x0036|if ((r0 instanceof kotlinx.coroutines.Incomplete) != false) goto L19\l}"];
Node_37 [shape=record,label="{37\:\ 0x0038}"];
Node_38 [shape=record,label="{38\:\ 0x003a|if ((r0 instanceof kotlinx.coroutines.CompletedExceptionally) == false) goto L17\l}"];
Node_39 [shape=record,label="{39\:\ 0x003c}"];
Node_44 [shape=record,label="{44\:\ ?|SYNTHETIC\lRETURN\l|return toCancellationException$default(r5, ((kotlinx.coroutines.CompletedExceptionally) r0).cause, null, 1, null)\l}"];
Node_40 [shape=record,label="{40\:\ 0x0047}"];
Node_41 [shape=record,label="{41\:\ 0x005c|RETURN\lORIG_RETURN\l|return new kotlinx.coroutines.JobCancellationException(kotlin.jvm.internal.Intrinsics.stringPlus(kotlinx.coroutines.DebugStrings.getClassSimpleName(r5), \" has completed normally\"), null, r5)\l}"];
Node_42 [shape=record,label="{42\:\ 0x005d}"];
Node_43 [shape=record,label="{43\:\ 0x006a|throw new java.lang.IllegalStateException(kotlin.jvm.internal.Intrinsics.stringPlus(\"Job is still new or active: \", r5).toString())\l}"];
MethodNode[shape=record,label="{public final java.util.concurrent.CancellationException kotlinx.coroutines.JobSupport.getCancellationException((r5v0 'this' kotlinx.coroutines.JobSupport A[IMMUTABLE_TYPE, THIS]))  | USE_LINES_HINTS\lCROSS_EDGE: B:41:0x005c \-\> B:24:?, CROSS_EDGE: B:28:0x0012 \-\> B:31:0x0023, CROSS_EDGE: B:39:0x003c \-\> B:41:0x005c, CROSS_EDGE: B:40:0x0047 \-\> B:41:0x005c, CROSS_EDGE: B:43:0x006a \-\> B:24:?\lINLINE_NOT_NEEDED\lTYPE_VARS: EMPTY\lMETHOD_OVERRIDE: [kotlinx.coroutines.Job.getCancellationException():java.util.concurrent.CancellationException]\l}"];
MethodNode -> Node_23;Node_23 -> Node_25;
Node_25 -> Node_26;
Node_26 -> Node_27[style=dashed];
Node_26 -> Node_35;
Node_27 -> Node_28;
Node_28 -> Node_30;
Node_28 -> Node_31[style=dashed];
Node_30 -> Node_31;
Node_31 -> Node_33;
Node_31 -> Node_45[style=dashed];
Node_33 -> Node_34;
Node_34 -> Node_24;
Node_45 -> Node_24;
Node_35 -> Node_36;
Node_36 -> Node_37[style=dashed];
Node_36 -> Node_42;
Node_37 -> Node_38;
Node_38 -> Node_39[style=dashed];
Node_38 -> Node_40;
Node_39 -> Node_44;
Node_44 -> Node_24;
Node_40 -> Node_41;
Node_41 -> Node_24;
Node_42 -> Node_43;
Node_43 -> Node_24;
}

